import { sql } from 'drizzle-orm';
import {
  index,
  jsonb,
  pgTable,
  timestamp,
  varchar,
  integer,
  text,
  boolean,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";
import { createInsertSchema } from "drizzle-zod";
import { z } from "zod";

// Session storage table - mandatory for Replit Auth
export const sessions = pgTable(
  "sessions",
  {
    sid: varchar("sid").primaryKey(),
    sess: jsonb("sess").notNull(),
    expire: timestamp("expire").notNull(),
  },
  (table) => [index("IDX_session_expire").on(table.expire)],
);

// User storage table - mandatory for Replit Auth
export const users = pgTable("users", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  email: varchar("email").unique(),
  firstName: varchar("first_name"),
  lastName: varchar("last_name"),
  profileImageUrl: varchar("profile_image_url"),
  role: varchar("role").notNull().default("public"), // public, doctor, admin
  region: varchar("region"), // for regional health tracking
  totalPoints: integer("total_points").notNull().default(0),
  level: integer("level").notNull().default(1),
  streak: integer("streak").notNull().default(0),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export type UpsertUser = typeof users.$inferInsert;
export type User = typeof users.$inferSelect;

// Prescription data collected by doctors
export const prescriptions = pgTable("prescriptions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  doctorId: varchar("doctor_id").notNull().references(() => users.id),
  ageGroup: varchar("age_group").notNull(), // 0-5, 6-12, 13-18, 19-40, 41-60, 60+
  gender: varchar("gender").notNull(), // male, female, other
  diagnosis: varchar("diagnosis").notNull(), // disease name
  symptoms: text("symptoms").array(),
  region: varchar("region").notNull(),
  severity: varchar("severity").notNull().default("moderate"), // mild, moderate, severe
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertPrescriptionSchema = createInsertSchema(prescriptions).omit({
  id: true,
  createdAt: true,
});

export type InsertPrescription = z.infer<typeof insertPrescriptionSchema>;
export type Prescription = typeof prescriptions.$inferSelect;

// Health alerts generated by the system
export const healthAlerts = pgTable("health_alerts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  disease: varchar("disease").notNull(),
  region: varchar("region").notNull(),
  severity: varchar("severity").notNull(), // low, medium, high, critical
  caseCount: integer("case_count").notNull(),
  message: text("message").notNull(), // AI-generated alert message
  preventiveMeasures: text("preventive_measures").array(),
  symptoms: text("symptoms").array(),
  isActive: boolean("is_active").notNull().default(true),
  createdAt: timestamp("created_at").defaultNow(),
  expiresAt: timestamp("expires_at"),
});

export const insertHealthAlertSchema = createInsertSchema(healthAlerts).omit({
  id: true,
  createdAt: true,
});

export type InsertHealthAlert = z.infer<typeof insertHealthAlertSchema>;
export type HealthAlert = typeof healthAlerts.$inferSelect;

// Disease information and educational content
export const diseases = pgTable("diseases", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  name: varchar("name").notNull().unique(),
  category: varchar("category").notNull(), // communicable, seasonal, chronic
  description: text("description").notNull(),
  symptoms: text("symptoms").array(),
  preventiveMeasures: text("preventive_measures").array(),
  treatment: text("treatment"),
  severity: varchar("severity").notNull(), // mild, moderate, severe
  season: varchar("season"), // summer, monsoon, winter, year-round
  iconName: varchar("icon_name"), // lucide icon name
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertDiseaseSchema = createInsertSchema(diseases).omit({
  id: true,
  createdAt: true,
});

export type InsertDisease = z.infer<typeof insertDiseaseSchema>;
export type Disease = typeof diseases.$inferSelect;

// Quiz questions for gamified learning
export const quizQuestions = pgTable("quiz_questions", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  diseaseId: varchar("disease_id").notNull().references(() => diseases.id),
  question: text("question").notNull(),
  options: text("options").array().notNull(),
  correctAnswer: integer("correct_answer").notNull(), // index of correct option
  explanation: text("explanation"),
  difficulty: varchar("difficulty").notNull().default("medium"), // easy, medium, hard
  points: integer("points").notNull().default(10),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertQuizQuestionSchema = createInsertSchema(quizQuestions).omit({
  id: true,
  createdAt: true,
});

export type InsertQuizQuestion = z.infer<typeof insertQuizQuestionSchema>;
export type QuizQuestion = typeof quizQuestions.$inferSelect;

// User quiz progress and achievements
export const userProgress = pgTable("user_progress", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  diseaseId: varchar("disease_id").notNull().references(() => diseases.id),
  questionsAttempted: integer("questions_attempted").notNull().default(0),
  questionsCorrect: integer("questions_correct").notNull().default(0),
  totalPoints: integer("total_points").notNull().default(0),
  completed: boolean("completed").notNull().default(false),
  lastAttemptedAt: timestamp("last_attempted_at").defaultNow(),
});

export const insertUserProgressSchema = createInsertSchema(userProgress).omit({
  id: true,
  lastAttemptedAt: true,
});

export type InsertUserProgress = z.infer<typeof insertUserProgressSchema>;
export type UserProgress = typeof userProgress.$inferSelect;

// Quiz attempts for tracking
export const quizAttempts = pgTable("quiz_attempts", {
  id: varchar("id").primaryKey().default(sql`gen_random_uuid()`),
  userId: varchar("user_id").notNull().references(() => users.id),
  questionId: varchar("question_id").notNull().references(() => quizQuestions.id),
  selectedAnswer: integer("selected_answer").notNull(),
  isCorrect: boolean("is_correct").notNull(),
  pointsEarned: integer("points_earned").notNull().default(0),
  createdAt: timestamp("created_at").defaultNow(),
});

export const insertQuizAttemptSchema = createInsertSchema(quizAttempts).omit({
  id: true,
  createdAt: true,
});

export type InsertQuizAttempt = z.infer<typeof insertQuizAttemptSchema>;
export type QuizAttempt = typeof quizAttempts.$inferSelect;

// Define relations
export const usersRelations = relations(users, ({ many }) => ({
  prescriptions: many(prescriptions),
  progress: many(userProgress),
  attempts: many(quizAttempts),
}));

export const prescriptionsRelations = relations(prescriptions, ({ one }) => ({
  doctor: one(users, {
    fields: [prescriptions.doctorId],
    references: [users.id],
  }),
}));

export const diseasesRelations = relations(diseases, ({ many }) => ({
  quizQuestions: many(quizQuestions),
  progress: many(userProgress),
}));

export const quizQuestionsRelations = relations(quizQuestions, ({ one, many }) => ({
  disease: one(diseases, {
    fields: [quizQuestions.diseaseId],
    references: [diseases.id],
  }),
  attempts: many(quizAttempts),
}));

export const userProgressRelations = relations(userProgress, ({ one }) => ({
  user: one(users, {
    fields: [userProgress.userId],
    references: [users.id],
  }),
  disease: one(diseases, {
    fields: [userProgress.diseaseId],
    references: [diseases.id],
  }),
}));

export const quizAttemptsRelations = relations(quizAttempts, ({ one }) => ({
  user: one(users, {
    fields: [quizAttempts.userId],
    references: [users.id],
  }),
  question: one(quizQuestions, {
    fields: [quizAttempts.questionId],
    references: [quizQuestions.id],
  }),
}));
